openapi: 3.0.0
info:
  title: procure
  version: '1.0'
  description: 'API spécifique "La Procure"'
servers:
  - url: 'https://api.electre.com/v1.0'
    description: Environnement de production
paths:
  '/books/{id-or-ean}':
    parameters:
      - schema:
          type: string
        name: id-or-ean
        in: path
        required: true
        description: EAN ou identifiant de la notice
    get:
      summary: "Récuperation d'une notice"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                Notice par identifiant/EAN:
                  $ref: '#../assets/Procure/Procure/books-by-id.json'
                  value:
                    _links:
                      - href: 'https://api.electre.com/v1.0/books/0-2335675'
                        rel: self
                      - href: 'https://api.electre.com/v1.0/books/0-2335675/covers/9782809710472?alt=media'
                        rel: coverMedia
                    auteurs:
                      - contribution: Auteur
                        formeBib: 'Lewis, Norman'
                        id: 0-1431375
                        nationalité: Royaume-Uni
                        nom: Norman Lewis
                    catalog: livre
                    clils:
                      - code: '3640'
                        libellé: Littérature générale -- Récits de voyages
                    collections:
                      - id: 0-21198
                        libellé: Picquier poche
                    contributeurs:
                      - contribution: Traducteur
                        formeBib: 'Feldman-Garcia, Katherine'
                        id: 0-1666155
                        langue: anglais
                        nom: Katherine Feldman-Garcia
                    dateParution: '2014-10-21T00:00:00'
                    description:
                      hauteur: 17
                      largeur: 11
                      nbPages: 435
                      épaisseur: 2.1
                    disponibilité: manquant
                    distributeurs:
                      - gln: '3012902940000'
                        id: 0-413266
                        nom: Harmonia mundi
                    droits: []
                    eans:
                      - '9782809710472'
                    eansCouverture:
                      - '9782809710472'
                    flagScolaire: false
                    formatNumérique: ''
                    id: 0-2335675
                    isbns:
                      - 2-8097-1047-3
                      - 978-2-8097-1047-2
                    poids: 272
                    prix:
                      devise: EUR
                      hts:
                        - 8.53
                      ttc: 9
                      tvas:
                        - 5.5
                    procure:
                      codeDisponibilité: NDI
                      codeFamille: W-952
                      codeGenre: W-1
                      codeSousFamille: P-610-75
                      codeSousSousFamille: P-610-75-36
                      poids: '0'
                      prixHT: '8,53'
                      prixPromo: '0'
                      prixTTC: '9,00'
                      typeProduit: L
                      ventes: '0'
                    protection: ''
                    publics:
                      - code: PG0100
                        libellé: Grand public -- Tout public
                    quatrièmeDeCouverture: |-
                      En janvier 1950, le journaliste et écrivain
                      Norman Lewis part pour Saigon, à l'époque où les trois pays de l'Indochine française se libèrent de la tutelle coloniale. Pris au coeur de la tourmente, ce n'est pourtant pas seulement en observateur des conflits qu'il est venu. Ce qui l'attire, au risque de sa vie, ce sont les derniers témoignages de traditions ancestrales, dont il pressent la prochaine disparition. Du Vietnam au Cambodge et au Laos, il raconte les modes de vie, les formes d'art et d'architecture, les pratiques religieuses et les coutumes des tribus les plus reculées. Avec une insatiable curiosité, tempérée par une nonchalance et un humour pince-sans-rire tout britanniques, qu'il sait nous faire partager.
                    reliure: Broché
                    résumé: "En 1949, l'auteur effectue un périple qui le mène de Saïgon jusqu'à l'extrême nord du Laos, en passant par les plateaux vietnamiens. Qu'il réalise une interview du roi du Cambodge ou montre les pratiques de la secte Cao-Dai, sa description, remplie d'un flegme et d'un humour typiquement britannique, montre une Indochine en pleine effervescence. ©Electre 2019"
                    source: electre
                    séries: []
                    titre: 'La nuit du dragon : voyage en Indochine'
                    éditeurs:
                      - id: 0-713738
                        libellé: P. Picquier
                    éditions:
                      - Nouvelle présentation
      operationId: get-books-id-or-ean
      description: 'Recupére une notice via son identifiant **ou** son EAN.'
      security:
        - id-electre:
            - webapi
      tags:
        - notice
      requestBody: {}
  '/books/{id}/covers':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Liste des couvertures pour une notice
      tags:
        - notice
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Liste des couvertures disponibles pour un identifiant notice:
                  value:
                    _links:
                      - href: 'https://api.electre.com/v1.0/books/0-2335675/covers'
                        rel: self
                    list:
                      - _links:
                          - href: 'https://api.electre.com/v1.0/books/0-2335675/covers/9782809710472'
                            rel: cover
                          - href: 'https://api.electre.com/v1.0/books/0-2335675/covers/9782809710472?alt=media'
                            rel: media
                        ean: '9782809710472'
                        id: 0-2335675
      operationId: get-books-id-or-ean-covers
      description: |-
        Liste des couvertures disponibles pour un ID donné.

        Si plusieurs couvertures sont disponibles, ellessont listées par EAN.
      security:
        - id-electre:
            - webapi
  '/books/{id}/covers/{ean}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
        schema:
          type: string
        description: Identifiant de la notice
      - type: string
        name: ean
        in: path
        required: true
        schema:
          type: string
        description: "EAN cible pour la notice d'identifiant `id`"
    get:
      summary: "Récupération d'une couverture"
      tags:
        - notice
      responses:
        '200':
          description: |-
            OK

            Le lien direct vers l'image de couverture est contenu dans le champ `href` pour la valeur `media` de `rel`.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Couverture par ID et EAN:
                  value:
                    _links:
                      - href: 'https://api.electre.com/v1.0/books/0-2335675/covers/9782809710472'
                        rel: self
                      - href: 'https://api.electre.com/v1.0/books/0-2335675/covers/9782809710472?alt=media'
                        rel: media
                    ean: '9782809710472'
                    id: 0-2335675
      operationId: get-books-id-covers-ean
      description: "Récupère la couverture pour la notice idenitifiée `id` et l'EAN."
      security:
        - id-electre:
            - webapi
      parameters:
        - schema:
            type: string
          in: query
          name: alt
          description: "`alt=media` retourne l'image au format JPEG directement"
        - schema:
            type: integer
            default: '400'
          in: query
          name: maxWidth
          description: "La largeur maximale de l'image en pixels"
        - schema:
            type: integer
          in: query
          name: maxHeight
          description: "La hauteur maximale de l'image en pixels"
  '/blacklist/{ean}':
    parameters:
      - type: string
        name: ean
        in: path
        required: true
        schema:
          type: string
        description: EAN cible
    get:
      summary: "Vérificiation d'appartenance à la blacklist"
      tags:
        - blacklist
        - beta
      responses:
        '204':
          description: "No Content: si l'EAN cible a été trouvé dans la blacklist"
        '404':
          description: "Not Found: si l'EAN cible n'est pas trouvé dans la blacklist"
      operationId: get-blacklist-ean
      description: "Vérifie si l'EAN donné est présent dans la blacklist."
      security:
        - idp electre:
            - webapi
    put:
      summary: "Ajout d'un élément à la blacklist"
      operationId: put-blacklist-ean
      responses:
        '201':
          description: "Created: Si l'ajout de l'EAN est un succés"
      description: "Ajoute l'EAN cible à la blacklist."
      security:
        - idp electre:
            - webapi
      tags:
        - blacklist
        - beta
    delete:
      summary: "Retrait d'un élément de la blacklist"
      operationId: delete-blacklist-ean
      responses:
        '200':
          description: "OK: si l'EAN a été supprimé de la blacklist"
        '404':
          description: "Not Found: Si l'EAN ne peut pas etre retiré de la blacklist (non-présent)"
      security:
        - idp electre:
            - webapi
      description: "Enlève l'EAN cible de la blacklist."
      tags:
        - blacklist
        - beta
components:
  schemas: {}
  securitySchemes:
    id-electre:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://idp2.electre.com/connect/token'
          refreshUrl: ''
          scopes:
            webapi: ''
